version: '3'
services:
  web1:
    container_name: app
    # platform: linux/amd64
    environment:
      - NODE_ENV=production
      - MARCH_BO_PORT=3000
      - MARCH_BO_AUTH_API_URL=http://0.0.0.0/api/auth/graphql
      - MARCH_BO_INVENTORY_API_URL=http://0.0.0.0/api/inventory/graphql
      - MARCH_BO_DEFAULT_LOGIN_PATH=/login
      - MARCH_BO_UAM_LOGIN_ENABLED=true
      - BASE_PATH=/backoffice
      - BACKOFFICE_TAG=0.1.0-1
    image: mbo-admin:${BACKOFFICE_TAG}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - 3000:3000
    x-bake:
      no-cache: true
  nginx:
    build: ./nginx
    ports:
      - '543:543'
    depends_on:
      - web1
